run:
  tests: true
  skip-dirs:
    - extern
  skip-files:
    - _test\.go
    - test/util.go

issues:
  exclude-rules:
    - linters:
        - wsl
      text: "branch statements should not be cuddled if block has more than two lines"
    - linters:
        - wsl
      text: "return statements should not be cuddled if block has more than two lines"

linters:
  enable-all: true
  disable:
    - typecheck
    - interfacer
    - structcheck
    - golint
    - ifshort
    - scopelint
    - varcheck
    - maligned
    - deadcode
    - structcheck
    - gci
    - goimports
    - gofumpt
    - nolintlint
    - ireturn
    - exhaustivestruct
    - nosnakecase
    - nlreturn
    - godox
    - gomoddirectives

linters-settings:
  wsl:
    allow-cuddle-declarations: true
    force-err-cuddling: true
  nilnil:
    checked-types:
      - func
      - iface
      - map
      - chan
  varnamelen:
    ignore-names:
      - ok
      - i
    ignore-decls:
      - db *gorm.DB
      - c testing.T
      - e error
      - t testing.T
      - c echo.Context
  paralleltest:
    ignore-missing: true
  funlen:
    lines: 180
    statements: 120
  cyclop:
    max-complexity: 20
  wrapcheck:
    ignoreSigRegexps:
      - \.JSON\(
      - \.NoContent\(
      - \.Error\(
  gomnd:
    ignored-numbers:
      - '0666'
      - '0755'
  exhaustruct:
    exclude:
      - 'task\.Definition'
      - 'gorm.*'
      - 'cli.*'
      - 'zerolog.*'
      - 'lecho.*'
      - '.*\.ResultContent'
      - '.*\.ResultModel'
      - 'module\.MinerInfoResult'
      - 'module\.ValidationResultModel'
      - 'module\.ValidationResult'
