name: Build and helper

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install FFI dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc-dev ocl-icd-opencl-dev traceroute python3-pip

      - name: Install jc
        run: sudo pip3 install jc

      - name: Deps
        run: make deps

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m

      - name: Setup postgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '13'
          postgresql db: 'postgres'
          postgresql user: 'postgres'
          postgresql password: 'postgres'
      - name: Setup gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run repo-specific setup
        uses: ./.github/workflows/actions/go-test-setup/

      - name: Test
        env:
          W3S_TOKEN_TEST: ${{ secrets.W3S_TOKEN_TEST }}
        run: $(go env GOPATH)/bin/gotestsum --format short

      - name: Docker build
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: docker build --build-arg GITHUB_TOKEN -t latest .
